import { string, z } from 'zod';

export const schema = z.object({
    id: string(),
    createdAt: z.date(),
    ownerId: z.string(),
    amSp: z.array(z.string()),
    amSt: z.array(z.string()),
    basePrice: z.number().int(),
    bathrooms: z.number().int(),
    bedrooms: z.number().int(),
    beds: z.number().int(),
    cleaningFee: z.number().int(),
    complete: z.boolean(),
    description: z.string(),
    events: z.boolean(),
    featured: z.boolean(),
    guests: z.number().int(),
    highlights: z.array(z.string()),
    icalFiles: z.array(z.string()),
    icalLinks: z.array(z.string()),
    locale: z.string(),
    locationType: z.array(z.string()),
    minNights: z.number().int(),
    onOffer: z.boolean(),
    parking: z.boolean(),
    placeName: z.string(),
    placeType: z.string(),
    slug: z.string(),
    smoking: z.boolean(),
    spaceType: z.string(),
    systemPublished: z.boolean(),
    title: z.string(),
    userPublished: z.boolean()
});